//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8825
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data.Entities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GEN", Namespace="http://schemas.datacontract.org/2004/07/Library.Data.Entities")]
    public partial class GEN : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Library.Data.Entities.CARTE[] CARTEsField;
        
        private string DescriereField;
        
        private int GenIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.CARTE[] CARTEs
        {
            get
            {
                return this.CARTEsField;
            }
            set
            {
                this.CARTEsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenId
        {
            get
            {
                return this.GenIdField;
            }
            set
            {
                this.GenIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARTE", Namespace="http://schemas.datacontract.org/2004/07/Library.Data.Entities")]
    public partial class CARTE : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Library.Data.Entities.AUTOR AUTORField;
        
        private int AutorIdField;
        
        private int CarteIdField;
        
        private Library.Data.Entities.GEN GENField;
        
        private int GenIdField;
        
        private Library.Data.Entities.IMPRUMUT[] IMPRUMUTsField;
        
        private string TitluField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.AUTOR AUTOR
        {
            get
            {
                return this.AUTORField;
            }
            set
            {
                this.AUTORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutorId
        {
            get
            {
                return this.AutorIdField;
            }
            set
            {
                this.AutorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarteId
        {
            get
            {
                return this.CarteIdField;
            }
            set
            {
                this.CarteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.GEN GEN
        {
            get
            {
                return this.GENField;
            }
            set
            {
                this.GENField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GenId
        {
            get
            {
                return this.GenIdField;
            }
            set
            {
                this.GenIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.IMPRUMUT[] IMPRUMUTs
        {
            get
            {
                return this.IMPRUMUTsField;
            }
            set
            {
                this.IMPRUMUTsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AUTOR", Namespace="http://schemas.datacontract.org/2004/07/Library.Data.Entities")]
    public partial class AUTOR : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AutorIdField;
        
        private Library.Data.Entities.CARTE[] CARTEsField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AutorId
        {
            get
            {
                return this.AutorIdField;
            }
            set
            {
                this.AutorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.CARTE[] CARTEs
        {
            get
            {
                return this.CARTEsField;
            }
            set
            {
                this.CARTEsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IMPRUMUT", Namespace="http://schemas.datacontract.org/2004/07/Library.Data.Entities")]
    public partial class IMPRUMUT : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Library.Data.Entities.CARTE CARTEField;
        
        private Library.Data.Entities.CITITOR CITITORField;
        
        private int CarteIdField;
        
        private int CititorIdField;
        
        private System.DateTime DataImprumutField;
        
        private System.Nullable<System.DateTime> DataRestituireField;
        
        private System.DateTime DataScadentaField;
        
        private int ImprumutIdField;
        
        private Library.Data.Entities.REVIEW[] REVIEWsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.CARTE CARTE
        {
            get
            {
                return this.CARTEField;
            }
            set
            {
                this.CARTEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.CITITOR CITITOR
        {
            get
            {
                return this.CITITORField;
            }
            set
            {
                this.CITITORField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarteId
        {
            get
            {
                return this.CarteIdField;
            }
            set
            {
                this.CarteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CititorId
        {
            get
            {
                return this.CititorIdField;
            }
            set
            {
                this.CititorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataImprumut
        {
            get
            {
                return this.DataImprumutField;
            }
            set
            {
                this.DataImprumutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataRestituire
        {
            get
            {
                return this.DataRestituireField;
            }
            set
            {
                this.DataRestituireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataScadenta
        {
            get
            {
                return this.DataScadentaField;
            }
            set
            {
                this.DataScadentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImprumutId
        {
            get
            {
                return this.ImprumutIdField;
            }
            set
            {
                this.ImprumutIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.REVIEW[] REVIEWs
        {
            get
            {
                return this.REVIEWsField;
            }
            set
            {
                this.REVIEWsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CITITOR", Namespace="http://schemas.datacontract.org/2004/07/Library.Data.Entities")]
    public partial class CITITOR : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AdresaField;
        
        private int CititorIdField;
        
        private string EmailField;
        
        private Library.Data.Entities.IMPRUMUT[] IMPRUMUTsField;
        
        private string NumeField;
        
        private string PrenumeField;
        
        private int StareField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adresa
        {
            get
            {
                return this.AdresaField;
            }
            set
            {
                this.AdresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CititorId
        {
            get
            {
                return this.CititorIdField;
            }
            set
            {
                this.CititorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.IMPRUMUT[] IMPRUMUTs
        {
            get
            {
                return this.IMPRUMUTsField;
            }
            set
            {
                this.IMPRUMUTsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stare
        {
            get
            {
                return this.StareField;
            }
            set
            {
                this.StareField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="REVIEW", Namespace="http://schemas.datacontract.org/2004/07/Library.Data.Entities")]
    public partial class REVIEW : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Library.Data.Entities.IMPRUMUT IMPRUMUTField;
        
        private int ImprumutIdField;
        
        private int ReviewIdField;
        
        private string TextField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Library.Data.Entities.IMPRUMUT IMPRUMUT
        {
            get
            {
                return this.IMPRUMUTField;
            }
            set
            {
                this.IMPRUMUTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ImprumutId
        {
            get
            {
                return this.ImprumutIdField;
            }
            set
            {
                this.ImprumutIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReviewId
        {
            get
            {
                return this.ReviewIdField;
            }
            set
            {
                this.ReviewIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text
        {
            get
            {
                return this.TextField;
            }
            set
            {
                this.TextField = value;
            }
        }
    }
}
namespace Library.Services.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Library.Services.Models")]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ErrorField;
        
        private int IdField;
        
        private string[] MessagesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ILibraryServices")]
public interface ILibraryServices
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetGenre", ReplyAction="http://tempuri.org/ILibraryServices/GetGenreResponse")]
    Library.Data.Entities.GEN GetGenre(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAuthor", ReplyAction="http://tempuri.org/ILibraryServices/GetAuthorResponse")]
    Library.Data.Entities.AUTOR GetAuthor(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetBook", ReplyAction="http://tempuri.org/ILibraryServices/GetBookResponse")]
    Library.Data.Entities.CARTE GetBook(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetLoan", ReplyAction="http://tempuri.org/ILibraryServices/GetLoanResponse")]
    Library.Data.Entities.IMPRUMUT GetLoan(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetReader", ReplyAction="http://tempuri.org/ILibraryServices/GetReaderResponse")]
    Library.Data.Entities.CITITOR GetReader(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetReview", ReplyAction="http://tempuri.org/ILibraryServices/GetReviewResponse")]
    Library.Data.Entities.REVIEW GetReview(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/VerifyGenreByDescription", ReplyAction="http://tempuri.org/ILibraryServices/VerifyGenreByDescriptionResponse")]
    Library.Data.Entities.GEN[] VerifyGenreByDescription(string numeGen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/VerifyAuthorByName", ReplyAction="http://tempuri.org/ILibraryServices/VerifyAuthorByNameResponse")]
    Library.Data.Entities.AUTOR[] VerifyAuthorByName(string numeAutor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/VerifyBookByTitle", ReplyAction="http://tempuri.org/ILibraryServices/VerifyBookByTitleResponse")]
    Library.Data.Entities.CARTE[] VerifyBookByTitle(string titluCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/VerifyReaderByName", ReplyAction="http://tempuri.org/ILibraryServices/VerifyReaderByNameResponse")]
    Library.Data.Entities.CITITOR[] VerifyReaderByName(string numeCititor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllGenres", ReplyAction="http://tempuri.org/ILibraryServices/GetAllGenresResponse")]
    Library.Data.Entities.GEN[] GetAllGenres();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllAuthors", ReplyAction="http://tempuri.org/ILibraryServices/GetAllAuthorsResponse")]
    Library.Data.Entities.AUTOR[] GetAllAuthors();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllBooks", ReplyAction="http://tempuri.org/ILibraryServices/GetAllBooksResponse")]
    Library.Data.Entities.CARTE[] GetAllBooks();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllLoans", ReplyAction="http://tempuri.org/ILibraryServices/GetAllLoansResponse")]
    Library.Data.Entities.IMPRUMUT[] GetAllLoans();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllReaders", ReplyAction="http://tempuri.org/ILibraryServices/GetAllReadersResponse")]
    Library.Data.Entities.CITITOR[] GetAllReaders();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllReviews", ReplyAction="http://tempuri.org/ILibraryServices/GetAllReviewsResponse")]
    Library.Data.Entities.REVIEW[] GetAllReviews();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetBookByTitle", ReplyAction="http://tempuri.org/ILibraryServices/GetBookByTitleResponse")]
    Library.Data.Entities.CARTE[] GetBookByTitle(string titluCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllBooksByGen", ReplyAction="http://tempuri.org/ILibraryServices/GetAllBooksByGenResponse")]
    Library.Data.Entities.CARTE[] GetAllBooksByGen(string genCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllBooksByAuthor", ReplyAction="http://tempuri.org/ILibraryServices/GetAllBooksByAuthorResponse")]
    Library.Data.Entities.CARTE[] GetAllBooksByAuthor(string numeAutor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetBooksByAuthorTitle", ReplyAction="http://tempuri.org/ILibraryServices/GetBooksByAuthorTitleResponse")]
    Library.Data.Entities.CARTE[] GetBooksByAuthorTitle(string numeAutor, string titluCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetBooksByGenreAuthorTitle", ReplyAction="http://tempuri.org/ILibraryServices/GetBooksByGenreAuthorTitleResponse")]
    Library.Data.Entities.CARTE[] GetBooksByGenreAuthorTitle(string numeGen, string numeAutor, string titluCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetLoanByBookTitleReaderId", ReplyAction="http://tempuri.org/ILibraryServices/GetLoanByBookTitleReaderIdResponse")]
    Library.Data.Entities.IMPRUMUT[] GetLoanByBookTitleReaderId(string titluCarte, int cititorId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetLoanByBookId", ReplyAction="http://tempuri.org/ILibraryServices/GetLoanByBookIdResponse")]
    Library.Data.Entities.IMPRUMUT[] GetLoanByBookId(int carteId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetNumberOfExistingBooksByTitle", ReplyAction="http://tempuri.org/ILibraryServices/GetNumberOfExistingBooksByTitleResponse")]
    int GetNumberOfExistingBooksByTitle(string titluCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetNumberOfBorrowedBooksByTitle", ReplyAction="http://tempuri.org/ILibraryServices/GetNumberOfBorrowedBooksByTitleResponse")]
    int GetNumberOfBorrowedBooksByTitle(string titluCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/ShowDateToBorrowBook", ReplyAction="http://tempuri.org/ILibraryServices/ShowDateToBorrowBookResponse")]
    System.DateTime ShowDateToBorrowBook(string titluCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllReadersByPeriodTime", ReplyAction="http://tempuri.org/ILibraryServices/GetAllReadersByPeriodTimeResponse")]
    string[] GetAllReadersByPeriodTime(System.DateTime dataStart, System.DateTime dataStop);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllRequestedBooks", ReplyAction="http://tempuri.org/ILibraryServices/GetAllRequestedBooksResponse")]
    string[] GetAllRequestedBooks();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllWantedAuthors", ReplyAction="http://tempuri.org/ILibraryServices/GetAllWantedAuthorsResponse")]
    string[] GetAllWantedAuthors();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetAllRequestedGenres", ReplyAction="http://tempuri.org/ILibraryServices/GetAllRequestedGenresResponse")]
    string[] GetAllRequestedGenres();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/GetReviewByBookTitle", ReplyAction="http://tempuri.org/ILibraryServices/GetReviewByBookTitleResponse")]
    string[] GetReviewByBookTitle(string titluCarte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/InsertGenre", ReplyAction="http://tempuri.org/ILibraryServices/InsertGenreResponse")]
    Library.Services.Models.Response InsertGenre(Library.Data.Entities.GEN gen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/InsertAuthor", ReplyAction="http://tempuri.org/ILibraryServices/InsertAuthorResponse")]
    Library.Services.Models.Response InsertAuthor(Library.Data.Entities.AUTOR autor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/InsertBook", ReplyAction="http://tempuri.org/ILibraryServices/InsertBookResponse")]
    Library.Services.Models.Response InsertBook(Library.Data.Entities.CARTE carte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/InsertLoan", ReplyAction="http://tempuri.org/ILibraryServices/InsertLoanResponse")]
    Library.Services.Models.Response InsertLoan(Library.Data.Entities.IMPRUMUT imprumut);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/InsertReader", ReplyAction="http://tempuri.org/ILibraryServices/InsertReaderResponse")]
    Library.Services.Models.Response InsertReader(Library.Data.Entities.CITITOR cititor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/InsertReview", ReplyAction="http://tempuri.org/ILibraryServices/InsertReviewResponse")]
    Library.Services.Models.Response InsertReview(Library.Data.Entities.REVIEW review);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/UpdateGenre", ReplyAction="http://tempuri.org/ILibraryServices/UpdateGenreResponse")]
    Library.Services.Models.Response UpdateGenre(Library.Data.Entities.GEN gen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/UpdateAuthor", ReplyAction="http://tempuri.org/ILibraryServices/UpdateAuthorResponse")]
    Library.Services.Models.Response UpdateAuthor(Library.Data.Entities.AUTOR autor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/UpdateBook", ReplyAction="http://tempuri.org/ILibraryServices/UpdateBookResponse")]
    Library.Services.Models.Response UpdateBook(Library.Data.Entities.CARTE carte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/UpdateLoan", ReplyAction="http://tempuri.org/ILibraryServices/UpdateLoanResponse")]
    Library.Services.Models.Response UpdateLoan(Library.Data.Entities.IMPRUMUT imprumut);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/UpdateReader", ReplyAction="http://tempuri.org/ILibraryServices/UpdateReaderResponse")]
    Library.Services.Models.Response UpdateReader(Library.Data.Entities.CITITOR cititor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/UpdateReview", ReplyAction="http://tempuri.org/ILibraryServices/UpdateReviewResponse")]
    Library.Services.Models.Response UpdateReview(Library.Data.Entities.REVIEW review);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/DeleteGenre", ReplyAction="http://tempuri.org/ILibraryServices/DeleteGenreResponse")]
    Library.Services.Models.Response DeleteGenre(Library.Data.Entities.GEN gen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/DeleteAuthor", ReplyAction="http://tempuri.org/ILibraryServices/DeleteAuthorResponse")]
    Library.Services.Models.Response DeleteAuthor(Library.Data.Entities.AUTOR autor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/DeleteBook", ReplyAction="http://tempuri.org/ILibraryServices/DeleteBookResponse")]
    Library.Services.Models.Response DeleteBook(Library.Data.Entities.CARTE carte);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/DeleteLoan", ReplyAction="http://tempuri.org/ILibraryServices/DeleteLoanResponse")]
    Library.Services.Models.Response DeleteLoan(Library.Data.Entities.IMPRUMUT imprumut);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/DeleteReader", ReplyAction="http://tempuri.org/ILibraryServices/DeleteReaderResponse")]
    Library.Services.Models.Response DeleteReader(Library.Data.Entities.CITITOR cititor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibraryServices/DeleteReview", ReplyAction="http://tempuri.org/ILibraryServices/DeleteReviewResponse")]
    Library.Services.Models.Response DeleteReview(Library.Data.Entities.REVIEW review);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ILibraryServicesChannel : ILibraryServices, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class LibraryServicesClient : System.ServiceModel.ClientBase<ILibraryServices>, ILibraryServices
{
    
    public LibraryServicesClient()
    {
    }
    
    public LibraryServicesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LibraryServicesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LibraryServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LibraryServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Library.Data.Entities.GEN GetGenre(int id)
    {
        return base.Channel.GetGenre(id);
    }
    
    public Library.Data.Entities.AUTOR GetAuthor(int id)
    {
        return base.Channel.GetAuthor(id);
    }
    
    public Library.Data.Entities.CARTE GetBook(int id)
    {
        return base.Channel.GetBook(id);
    }
    
    public Library.Data.Entities.IMPRUMUT GetLoan(int id)
    {
        return base.Channel.GetLoan(id);
    }
    
    public Library.Data.Entities.CITITOR GetReader(int id)
    {
        return base.Channel.GetReader(id);
    }
    
    public Library.Data.Entities.REVIEW GetReview(int id)
    {
        return base.Channel.GetReview(id);
    }
    
    public Library.Data.Entities.GEN[] VerifyGenreByDescription(string numeGen)
    {
        return base.Channel.VerifyGenreByDescription(numeGen);
    }
    
    public Library.Data.Entities.AUTOR[] VerifyAuthorByName(string numeAutor)
    {
        return base.Channel.VerifyAuthorByName(numeAutor);
    }
    
    public Library.Data.Entities.CARTE[] VerifyBookByTitle(string titluCarte)
    {
        return base.Channel.VerifyBookByTitle(titluCarte);
    }
    
    public Library.Data.Entities.CITITOR[] VerifyReaderByName(string numeCititor)
    {
        return base.Channel.VerifyReaderByName(numeCititor);
    }
    
    public Library.Data.Entities.GEN[] GetAllGenres()
    {
        return base.Channel.GetAllGenres();
    }
    
    public Library.Data.Entities.AUTOR[] GetAllAuthors()
    {
        return base.Channel.GetAllAuthors();
    }
    
    public Library.Data.Entities.CARTE[] GetAllBooks()
    {
        return base.Channel.GetAllBooks();
    }
    
    public Library.Data.Entities.IMPRUMUT[] GetAllLoans()
    {
        return base.Channel.GetAllLoans();
    }
    
    public Library.Data.Entities.CITITOR[] GetAllReaders()
    {
        return base.Channel.GetAllReaders();
    }
    
    public Library.Data.Entities.REVIEW[] GetAllReviews()
    {
        return base.Channel.GetAllReviews();
    }
    
    public Library.Data.Entities.CARTE[] GetBookByTitle(string titluCarte)
    {
        return base.Channel.GetBookByTitle(titluCarte);
    }
    
    public Library.Data.Entities.CARTE[] GetAllBooksByGen(string genCarte)
    {
        return base.Channel.GetAllBooksByGen(genCarte);
    }
    
    public Library.Data.Entities.CARTE[] GetAllBooksByAuthor(string numeAutor)
    {
        return base.Channel.GetAllBooksByAuthor(numeAutor);
    }
    
    public Library.Data.Entities.CARTE[] GetBooksByAuthorTitle(string numeAutor, string titluCarte)
    {
        return base.Channel.GetBooksByAuthorTitle(numeAutor, titluCarte);
    }
    
    public Library.Data.Entities.CARTE[] GetBooksByGenreAuthorTitle(string numeGen, string numeAutor, string titluCarte)
    {
        return base.Channel.GetBooksByGenreAuthorTitle(numeGen, numeAutor, titluCarte);
    }
    
    public Library.Data.Entities.IMPRUMUT[] GetLoanByBookTitleReaderId(string titluCarte, int cititorId)
    {
        return base.Channel.GetLoanByBookTitleReaderId(titluCarte, cititorId);
    }
    
    public Library.Data.Entities.IMPRUMUT[] GetLoanByBookId(int carteId)
    {
        return base.Channel.GetLoanByBookId(carteId);
    }
    
    public int GetNumberOfExistingBooksByTitle(string titluCarte)
    {
        return base.Channel.GetNumberOfExistingBooksByTitle(titluCarte);
    }
    
    public int GetNumberOfBorrowedBooksByTitle(string titluCarte)
    {
        return base.Channel.GetNumberOfBorrowedBooksByTitle(titluCarte);
    }
    
    public System.DateTime ShowDateToBorrowBook(string titluCarte)
    {
        return base.Channel.ShowDateToBorrowBook(titluCarte);
    }
    
    public string[] GetAllReadersByPeriodTime(System.DateTime dataStart, System.DateTime dataStop)
    {
        return base.Channel.GetAllReadersByPeriodTime(dataStart, dataStop);
    }
    
    public string[] GetAllRequestedBooks()
    {
        return base.Channel.GetAllRequestedBooks();
    }
    
    public string[] GetAllWantedAuthors()
    {
        return base.Channel.GetAllWantedAuthors();
    }
    
    public string[] GetAllRequestedGenres()
    {
        return base.Channel.GetAllRequestedGenres();
    }
    
    public string[] GetReviewByBookTitle(string titluCarte)
    {
        return base.Channel.GetReviewByBookTitle(titluCarte);
    }
    
    public Library.Services.Models.Response InsertGenre(Library.Data.Entities.GEN gen)
    {
        return base.Channel.InsertGenre(gen);
    }
    
    public Library.Services.Models.Response InsertAuthor(Library.Data.Entities.AUTOR autor)
    {
        return base.Channel.InsertAuthor(autor);
    }
    
    public Library.Services.Models.Response InsertBook(Library.Data.Entities.CARTE carte)
    {
        return base.Channel.InsertBook(carte);
    }
    
    public Library.Services.Models.Response InsertLoan(Library.Data.Entities.IMPRUMUT imprumut)
    {
        return base.Channel.InsertLoan(imprumut);
    }
    
    public Library.Services.Models.Response InsertReader(Library.Data.Entities.CITITOR cititor)
    {
        return base.Channel.InsertReader(cititor);
    }
    
    public Library.Services.Models.Response InsertReview(Library.Data.Entities.REVIEW review)
    {
        return base.Channel.InsertReview(review);
    }
    
    public Library.Services.Models.Response UpdateGenre(Library.Data.Entities.GEN gen)
    {
        return base.Channel.UpdateGenre(gen);
    }
    
    public Library.Services.Models.Response UpdateAuthor(Library.Data.Entities.AUTOR autor)
    {
        return base.Channel.UpdateAuthor(autor);
    }
    
    public Library.Services.Models.Response UpdateBook(Library.Data.Entities.CARTE carte)
    {
        return base.Channel.UpdateBook(carte);
    }
    
    public Library.Services.Models.Response UpdateLoan(Library.Data.Entities.IMPRUMUT imprumut)
    {
        return base.Channel.UpdateLoan(imprumut);
    }
    
    public Library.Services.Models.Response UpdateReader(Library.Data.Entities.CITITOR cititor)
    {
        return base.Channel.UpdateReader(cititor);
    }
    
    public Library.Services.Models.Response UpdateReview(Library.Data.Entities.REVIEW review)
    {
        return base.Channel.UpdateReview(review);
    }
    
    public Library.Services.Models.Response DeleteGenre(Library.Data.Entities.GEN gen)
    {
        return base.Channel.DeleteGenre(gen);
    }
    
    public Library.Services.Models.Response DeleteAuthor(Library.Data.Entities.AUTOR autor)
    {
        return base.Channel.DeleteAuthor(autor);
    }
    
    public Library.Services.Models.Response DeleteBook(Library.Data.Entities.CARTE carte)
    {
        return base.Channel.DeleteBook(carte);
    }
    
    public Library.Services.Models.Response DeleteLoan(Library.Data.Entities.IMPRUMUT imprumut)
    {
        return base.Channel.DeleteLoan(imprumut);
    }
    
    public Library.Services.Models.Response DeleteReader(Library.Data.Entities.CITITOR cititor)
    {
        return base.Channel.DeleteReader(cititor);
    }
    
    public Library.Services.Models.Response DeleteReview(Library.Data.Entities.REVIEW review)
    {
        return base.Channel.DeleteReview(review);
    }
}
